[tools]
aube = "latest"
bun = "latest"
"github:elide-dev/elide" = "1.4.4+20260824"
hk = "latest"
java = { version = "openjdk-25", install_env = { JAVA_TOOL_OPTIONS = "--enable-native-access=ALL-UNNAMED" } }
