[toolchain]
version = "2026-06-13"
channel = "nightly-2026-06-13"
profile = "default"

components = [
  "cargo",
  "clippy",
  "rust-analyzer",
  "rustc",
  "rustfmt",
  "rust-src",
  "rustc-dev",
  "llvm-tools-preview",
  "miri",
]
