[unstable]
sbom = true
profile-rustflags = true
build-std = ["std", "core", "alloc", "proc_macro", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
incremental = false
overflow-checks = false
trim-paths = "all"
codegen-units = 1
debug = true
split-debuginfo = "unpacked"

rustflags = [
  # Enable unstable options access.
  "-Zunstable-options",

  # MIR-level wins that compound across monomorphizations.
  "-Zinline-mir=yes",
  "-Zmir-opt-level=2",  # do NOT go to 3; persistent miscompiles
  "-Zshare-generics=y",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
  # Enforce completely position-independent executables.
  "-Crelocation-model=pic",

  # Target CPU.
  "-Ctarget-cpu=x86-64-v3",
]
